version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "anmac"
github_repo = "sync-step-function"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::597874789517:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-1WEFHlb0KCxB"
cloudformation_execution_role = "arn:aws:iam::597874789517:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-lbPuc8HKX6UR"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-nj91cksjghjg"
image_repository = ""
region = "us-east-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::597874789517:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-pKqIydEuOywK"
cloudformation_execution_role = "arn:aws:iam::597874789517:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-D9EsryH3V4Vi"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-gsy2peh7clzp"
image_repository = ""
region = "us-east-2"
